MODE = (('A', 'Active'), ('D', 'Deactive'), ('T', 'Trash'))
GENDER = (('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('Androgyny', 'Androgyny'))
APPROVAL = (('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected'))
PLATFORM = (('A', "Android"), ('I', "iOS"), ('W', "Web"))
SUBSCRIPTION_TYPE = (('M', "Monthly"), ('Q', "Quarterly"), ('Y', "Yearly"))
SUBSCRIPTION_PLAN_TYPE = (('Plan', 'Plan'), ('Add-on', 'Add-on'))
PAYMENT_STATUS = (('Paid', 'Paid'), ('Pending', 'Pending'))
